package com.wdp.sayHello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-23T15:06:58.223+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://wdp.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://wdp.com/", className = "com.wdp.sayHello.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://wdp.com/", className = "com.wdp.sayHello.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
